blog_mehran/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from account.views import Login, Register, activate
from blog_mehran import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myblog.urls')),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('weatherblog/', include('weather.urls')),

    # api
    path('api/posts/', include('myblog.api.urls')),
    path('api/account/', include('account.api.urls')),


    path('', include('django.contrib.auth.urls')),

    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,200})/$', activate,
            name='activate'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('', include('social_django.urls', namespace='social')),
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import re_path,path
from .views import (
    ArticleList,
    ArticleDetail,
    CategoryList,
    AuthorList,
    ArticlePreview,
    SearchList,)

app_name='blog'
urlpatterns = [
    path('blog/',ArticleList.as_view(),name='articleList'),
    path(r'blog/<int:page>',ArticleList.as_view(),name='articleList'),
    re_path(r'blog/(?P<slug>[-\w\d]+)/', ArticleDetail.as_view(), name="detail"),
    path('preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
    path('category/<slug:slug>',CategoryList.as_view(),name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
    path('search/', SearchList.as_view(), name="search"),
    path('search/page/<int:page>', SearchList.as_view(), name="search"),
]

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load base_tags %}
{% load comment_tags %}
{% load ratings %}
{% load humanize %}


<div class="culmn">
    <!--Home Sections-->
    <!--Blog Features Section-->
    {% block subhead %}
        <section id="blog_details" class="blog_details roomy-100">
        <div class="container">
        <div class="row">

        <div class="col-md-8">
            <div class="main_blog_details">
                {% block detail %}
                    <div class="blog_details_left">
                        <div class="blog_details_img">
                            <img src="{{ object.thumbnail.url }}" alt=""/>
                        </div>
                        <div class="blog_details_content">
                            <div class="blog_details_head m-top-40">
                                <div class="blog_date">
                                    <span>29</span> <br/>
                                    <span>Jan</span>
                                </div>
                                <div class="head_text">
                                    <h2>{{ object.title }}</h2>
                                    <ul class="list-inline">
                                        <li><a href="{% url 'blog:author' object.author.username %}"
                                               class="text-black">{{ object.author.get_full_name }}</a></li>
                                        <li><h5 class="text-black">{{ object.jpublish }}</h5></li>
                                        {% if object.is_special %}
                                            <span class="badge"
                                                  style="background-color: red">مقاله ویژه</span>
                                        {% endif %}
                                    <br/>
                                    <div>{% ratings object %}</div>
                                    <p>بازدید:{{ object.hits.count }}نفر</p>
                                    </ul>
                                </div>
                            </div>
                            <div class="blog_details_figure m-top-40">
                                {% if object.is_special %}
                                    {% if user.is_authenticated and user.is_special or user == object.author or user.is_superuser %}
                                        {{ object.description|safe }}
                                    {% else %}
                                        {{ object.description|truncatewords:"50"|safe }}
                                        <p class="alert alert-warning">این مقاله ویژه است و برای مشاهده آن
                                            باید <a href="#">اشتراک
                                                ویژه</a> تهیه نمایید </p>
                                    {% endif %}
                                {% else %}
                                    <p>{{ object.description|safe }}</p>
                                {% endif %}
                            </div>


                            <div class="socail_share text-right m-top-60">
                                <ul class="list-inline text-uppercase">
                                    <li>اشتراک گذاری پست</li>
                                    <li><a href=""><i class="fa fa-facebook"></i></a></li>
                                    <li><a href=""><i class="fa fa-twitter"></i></a></li>
                                    <li><a href=""><i class="fa fa-pinterest"></i></a></li>
                                    <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href=""><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endblock %}

                <hr/>

                {% block comment %}
                    {% render_comments object request %}
                {% endblock %}


            </div>
        </div><!-- End off col-md-8 -->

    <div class="col-md-4">
        <div class="blog_saidbar sm-m-top-70">
            {% block categorys %}
                <div class="said_ctg fix">
                    <h6 class="text-uppercase">دسته بندی این مقاله</h6>
                    <ul class="text-uppercase m-top-40">
                        {% for cat in object.category.active %}
                            <li><a href="{% url 'blog:category' cat.slug %}">{{ cat.title }}</a></li>
                        {% endfor %}
                    </ul>
                    <br/>
                    <br/>
                    {% category_navbar %}
                </div>
            {% endblock %}
            {% block resent_post %}
                <div class="said_post fix m-top-70">
                    <h6 class="m-bottom-40 text-uppercase">مقاله های پر بازدید اخیر</h6>
                    {% for a in res_articles %}
                        <div class="post_item">
                            <div class="item_img">
                                <img src="{{ a.thumbnail.url }}" alt=""/>
                            </div>
                            <div class="item_text">
                                <a href="{% url 'blog:detail' a.slug %}"><h6>{{ a.title }}</h6></a>
                                {% if a.is_special %}
                                    <span class="badge" style="background-color: red">مقاله ویژه</span>
                                {% endif %}
                                <p><i class="fa fa-clock-o"></i> {{ a.publish|naturaltime }}</p>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            {% endblock %}
        </div>
    </div><!-- End off col-md-4 -->


    </div><!-- End off row -->


    </div><!-- End off container -->
    </section><!-- End off blog Fashion -->
    {% endblock %}
</div>

templates/blog/article_list.html
{% extends 'blog/list.html' %}
{% load static %}
{% load base_tags %}
{% load ratings %}
{% load humanize %}


{% block title %}
    وبلاگ شخصی
{% endblock %}



{% block latest_articel %}
    {% for latest in object_list %}
        {% if forloop.first %}
            <div class="col-md-8">
                <div class="blog_fashion_left">
                    <div class="blog_fashion_img">
                        <img src="{{ latest.thumbnail.url }}" alt=""/>
                    </div>
                    <div class="blog_fashion_content">
                        <div>{% ratings latest %}</div>
                        <p>بازدید:{{ latest.hits.count }}نفر</p>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'blog:author' latest.author.username %}"
                                   class="text-black">{{ latest.author.get_full_name }}</a></li>
                            <li><a href="{% url 'blog:author' latest.author.username %}"
                                   class="text-black">{{ latest.publish|naturaltime }}</a></li>
                            {% if latest.is_special %}
                                <span class="badge" style="background-color: red">مقاله ویژه</span>
                            {% endif %}

                        </ol>
                        <h2>{{ latest.title }}</h2>
                        <p>{{ latest.description|truncatewords:70 |safe }}</p>
                        <a href="{% url 'blog:detail' latest.slug %}" class="btn btn-default m-top-20"> مشاهده مقاله <i
                                class="fa fa-long-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        {% endif %}
    {% empty %}
    {% endfor %}
{% endblock %}

{% block owner_blog %}
    <div class="col-md-4">
        <div class="blog_fashion_right">
            <div class="said_ctg fix">
                {% category_navbar %}
            </div>
        </div>
    </div>
{% endblock %}

{% block article_list %}
    {% block categorys_name %}
    {% endblock %}
    <div class="row">
        <div class="blog_area fix">
            {% for article in object_list %}
                <div class="col-md-4">
                    <div class="blog_item m-top-30">
                        <div class="blog_item_img">
                            <img src="{{ article.thumbnail.url }}" alt=""/>
                        </div>
                        <ol class="breadcrumb">
                            <li><a href="{% url 'blog:author' article.author.username %}"
                                   class="text-black">{{ article.author.get_full_name }}</a></li>
                            <li><a href="{% url 'blog:author' article.author.username %}"
                                   class="text-black">{{ article.publish|naturaltime }}</a></li>
                            {% if article.is_special %}
                                <span class="badge" style="background-color: red">مقاله ویژه</span>
                            {% endif %}
                        </ol>
                        <div>{% ratings article %}</div>
                        <p>بازدید:{{ article.hits.count }}نفر</p>
                        <a href="{% url 'blog:detail' article.slug %}"><h5>{{ article.title }}</h5></a>

                        <p class="m-top-20">{{ article.description|truncatewords:20|safe }}</p>
                    </div>
                </div><!-- End off col-md-4 -->
            {% empty %}
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <p style="text-align: center !important;">متاسفانه هیچ مقاله ای وجود ندارد</p>
                </div>
                <div class="col-md-4"></div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

{% block previous_page_url %}
    {% url 'blog:articleList' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:articleList' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/article_list.html' %}

{% block categorys_name %}
    <h3 class="alert alert-primary text-center">نویسنده: {{ author.get_full_name }}</h3>
{% endblock %}
{% block previous_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}

<!doctype html>

<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}">

    <!--Google Fonts link-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600,600i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonticons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootsnav.css' %}">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--For Plugins external css-->
    <!--<link rel="stylesheet" href="assets/css/plugins.css" />-->

    <!--Theme custom css -->
    {% block img_css %}

    {% endblock %}
    <!--<link rel="stylesheet" href="assets/css/colors/maron.css">-->

    <!--Theme Responsive css-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}"/>

    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
</head>
<style>

    #nav ul {
        padding-right: 0;
        height: 30px;
        width: 120px;
    }

    #nav ul li {
        border-bottom: none;
        height: 30px;
        width: 120px;
        line-height: 30px;
        font-size: 30px;
        display: inline-block;
        float: left;
        margin: 0 auto;
    }

    #nav ul li a {
        text-decoration: none;
        color: #000000;
        display: block;
        transition: .3s background-color;
        padding: 0 24px;
    }

    #nav ul li a:hover {
        background-color: #515d68;
        color: #FFFFFF;
    }

    #nav a {
        border-bottom: none;
    }

    #nav li ul {
        position: absolute;
        display: none;
        width: inherit;
    }

    #nav li:hover ul {
        display: block;
    }

    #nav ul li ul li {
        display: block;
        float: none !important; /* newly added */
        height: auto; /* newly added */
        line-height: 34px; /* newly added */
    }

    #nav ul li ul li ul {
        position: absolute;
        right: 100%;
        top: 0;
        display: none !important;
    }

    #nav ul > li > ul > li:hover > ul {
        display: block !important;
    }

    #nav ul > li > ul > li > ul > li:hover > ul {
        display: block !important;
    }

</style>
<body style="direction: rtl" data-spy="scroll" data-target=".navbar-collapse">

<div class="culmn">
    <!--Home page style-->
    <nav class="navbar navbar-default navbar-fixed white no-background bootsnav text-uppercase">
        <form class="top-search" action="{% url 'blog:search' %}">
            <div class="container">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input type="text" name="q" class="form-control" placeholder="جستوجو">
                    <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
                </div>
            </div>
        </form>
        <!-- End Top Search -->

        <div class="container">
            <!-- Start Atribute Navigation -->
            <div class="attr-nav">
                <ul>
                    <li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
                </ul>
            </div>
            <!-- End Atribute Navigation -->
            <!-- Start Header Navigation -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                    <i class="fa fa-bars"></i>
                </button>

            </div>
            <!-- End Header Navigation -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-menu">
                <ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
                    <li><a href="../index.html">home</a></li>
                    <li><a href="../aboutus.html">about</a></li>
                    <li><a href="../model.html">our models</a></li>
                    <li><a href="{% url 'blog:articleList' %}">وبلاگ</a></li>
                    <li><a href="">تماس با ما</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>
    <!--Home Sections-->
    <section id="hello" class="blog-banner bg-mega">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="main_home text-center">
                    <div class="about_text">
                        <h1 class="text-white text-uppercase">{%  title %}</h1>
                        <ol class="breadcrumb">
                            <li><a href="../index.html">{% block bala %}خانه{% endblock %}</a></li>
                            <li class="active"><a href="{% url 'blog:articleList' %}">وبلاگ</a></li>
                        </ol>
                    </div>
                </div>
            </div><!--End off row-->
        </div><!--End off container -->
    </section> <!--End off Home Sections-->

    {% block subhead %}
        {% block detail %}
        {% endblock %}

        {% block comment %}
        {% endblock %}

        {% block categorys %}
        {% endblock %}

        {% block resent_post %}
        {% endblock %}

    {% endblock %}


    <!--Company section-->
    <section id="company" class="company bg-light">
        <div class="container">
            <div class="row">
                <div class="main_company roomy-100 text-center">
                    <h3 class="text-uppercase">{{ owner.comp }}</h3>
                    <p>{{ owner.uni }}</p>
                    <p>{{ owner.email }}</p>
                </div>
            </div>
        </div>
    </section>


    <!-- scroll up-->
    <div class="scrollup">
        <a href="#"><i class="fa fa-chevron-up"></i></a>
    </div><!-- End off scroll up -->


    <footer id="footer" class="footer bg-mega">
        <div class="container">
            <div class="row">
                <div class="main_footer p-top-40 p-bottom-30">
                    <div class="col-md-6 text-left sm-text-center">
                        <p class="wow fadeInRight" data-wow-duration="1s">
                            create by
                            <i class="fa fa-heart"></i>
                            mehran kamrani
                        </p>
                    </div>
                    <div class="col-md-6 text-right sm-text-center sm-m-top-20">
                        <ul class="list-inline">
                            <li><a href="{{ owner.github }}">گیتهاب</a></li>
                            <li><a href="{{ owner.wat }}">واتساپ</a></li>
                            <li><a href="{{ owner.insta }}">اینستاگرام</a></li>
                            <li><a href="{{ owner.tel }}">تلگرام</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</div>

<!-- JS includes -->

<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

<script src="{% static 'js/isotope.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/jquery.collapse.js' %}"></script>
<script src="{% static 'js/bootsnav.js' %}"></script>
<script src="{% static 'js/masonry.min.js' %}"></script>

<script type="text/javascript">
    var msnry = new Masonry('.blog_area');
</script>

<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block add_script %}
{% endblock %}

</body>
</html>

templates/blog/category.html
{% extends 'blog/article_list.html' %}

{% block categorys_name %}
    <h3 class="alert alert-primary text-center">دسته بندی: {{ category.title }}</h3>
{% endblock %}
{% block previous_page_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/category_list.html
{% extends 'blog/article_list.html' %}

{% block categorys_name %}
    <h3 class="alert alert-primary text-center">دسته بندی: {{ category.title }}</h3>
{% endblock %}
{% block previous_page_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/contactus.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    تماس با ما
{% endblock %}

{% block bala %}
    تماس با ما
{% endblock %}

<div class="culmn">
    {% block contactus %}
        <!--Call To Action Section-->
        <section id="action" class="action roomy-100">
            <div class="container">
                <div class="row">
                    <div class="main_action text-center">
                        <div class="col-md-4">
                            <div class="action_item">
                                <i class="fa fa-map-marker"></i>
                                <h4 class="text-uppercase m-top-20">آدرس</h4>
                                <p>{{ object_list.address }}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="action_item">
                                <i class="fa fa-headphones"></i>
                                <h4 class="text-uppercase m-top-20">گیتهاب</h4>
                                <p>{{ object_list.github }}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="action_item">
                                <i class="fa fa-envelope-o"></i>
                                <h4 class="text-uppercase m-top-20">ایمیل</h4>
                                <p>{{ object_list.email }} <br/>
                                    {{ object_list.email2 }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <!-- map section-->
        <div id="map" class="map">
            <div class="ourmap"></div>
        </div><!-- End off Map section-->

        <!-- scroll up-->
        <div class="scrollup">
            <a href="#"><i class="fa fa-chevron-up"></i></a>
        </div><!-- End off scroll up -->


        </div>
    {% endblock %}


<!-- paradise slider js -->
{% block add_script %}
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyD_tAQD36pKp9v4at5AnpGbvBUsLCOSJx8"></script>
    <script src="{% static 'js/gmaps.min.js' %}"></script>
    <script>
        var map = new GMaps({
            el: '.ourmap',
            lat: 35.715298,
            lng: 51.404343,
            scrollwheel: false,
            zoom: 15,
            zoomControl: true,
            panControl: false,

            streetViewControl: false,
            mapTypeControl: false,
            overviewMapControl: false,
            clickable: false,
            styles: [{
                'stylers': [{'hue': 'gray'}, {saturation: -100},
                    {gamma: 0.80}]
            }]
        });

    </script>

{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}

{% block subhead %}
    <section id="blog_fashion" class="blog_fashion roomy-100">
        <div class="container">
            <div class="row">
                <div class="main_blog_fashion">
                    {% block latest_articel %}
                    {% endblock %}

                    {% block owner_blog %}
                    {% endblock %}

                </div>

            </div><!-- End off row -->

            <hr/>
            {% block article_list %}
            {% endblock %}
            {% if is_paginated %}
                <div class="clearfix ">
                    {% if page_obj.has_previous %}
                        <a class="btn btn-primary float-right ml-5 "
                           href="{% block previous_page_url %} {% endblock %}">مطالب جدید &rarr;</a> {% endif %}
                    {% if page_obj.has_next %}
                        <a class="btn btn-primary float-right ml-5" href="{% block next_page_url %} {% endblock %}">مطالب
                            قدیمی &larr;</a> {% endif %}
                </div>
            {% endif %}
        </div><!-- End off container -->
    </section><!-- End off blog Fashion -->
{% endblock %}

templates/blog/search_list.html
{% extends 'blog/article_list.html' %}

{% block categorys_name %}
    <h3 class="alert alert-primary text-center">جست و جو: {{ search }}</h3>
{% endblock %}
{% block previous_page_url %}
    {% url 'blog:search' page_obj.previous_page_number %}?q={{ search }}
{% endblock %}
{% block next_page_url %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{ search }}
{% endblock %}