blog_mehran/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from account.views import Login, Register, activate
from blog_mehran import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myblog.urls')),
    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('weatherblog/', include('weather.urls')),

    # api
    path('api/posts/', include('myblog.api.urls')),
    path('api/account/', include('account.api.urls')),


    path('', include('django.contrib.auth.urls')),

    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,200})/$', activate,
            name='activate'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('', include('social_django.urls', namespace='social')),
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import re_path,path
from .views import (
    ArticleList,
    ArticleDetail,
    CategoryList,
    AuthorList,
    ArticlePreview,
    SearchList,)

app_name='blog'
urlpatterns = [
    path('blog/',ArticleList.as_view(),name='articleList'),
    path(r'blog/<int:page>',ArticleList.as_view(),name='articleList'),
    re_path(r'blog/(?P<slug>[-\w\d]+)/', ArticleDetail.as_view(), name="detail"),
    path('preview/<int:pk>', ArticlePreview.as_view(), name="preview"),
    path('category/<slug:slug>',CategoryList.as_view(),name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('author/<slug:username>', AuthorList.as_view(), name="author"),
    path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
    path('search/', SearchList.as_view(), name="search"),
    path('search/page/<int:page>', SearchList.as_view(), name="search"),
]

weather/urls.py
from django.urls import path
from .views import index,delete_city

app_name='weather'
urlpatterns = [
    path('', index,name='weather_home'),
    path('delete/<str:city_name>', delete_city,name='delete_city'),
]

weather/models.py
from django.db import models

# Create your models here.
class City(models.Model):
    name=models.CharField(max_length=25,verbose_name='نام شهر')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='شهر'
        verbose_name_plural='شهرها'

weather/forms.py
from django.forms import TextInput,ModelForm
from .models import City

class CityForm(ModelForm):
    class Meta:
        model=City
        fields=['name']
        widgets={'name':TextInput(attrs={'class':'form-control input','placeholder':'نام شهر خود را به لاتین وارد نمایید مانند:Tehran'})}

weather/views.py
import requests
from django.shortcuts import render,redirect
from .models import City
from .forms import CityForm

# Create your views here.

#https://openweathermap.org/current
def index(request):
    url='http://api.openweathermap.org/data/2.5/weather?q={}&units=imperials&appid=bd4331ae65a371e51693fb6f1b43fc28'

    err_msg=''
    message=''
    message_class=''

    if request.method=='POST':
        form=CityForm(request.POST)
        if form.is_valid():
            new_city=form.cleaned_data['name']
            existing_city_count=City.objects.filter(name=new_city).count()
            if existing_city_count == 0:
                r = requests.get(url.format(new_city)).json()
                if r['cod']==200:
                    form.save()
                else:
                    err_msg='این شهر وجود ندارد'
            else:
                err_msg='این شهر از قبل وجود دارد'


        if err_msg:
            message=err_msg
            message_class='is_danger'
        else:
            message='این شهر با موفقیت وارد شد'
            message_class='is-success'

    form=CityForm()

    cities=City.objects.all().order_by('name')
    cities_whether=[]


    for city in cities:
        r = requests.get(url.format(city.name)).json()
        city_weather={
            'city':city.name,
            'temperature':r['main']['temp'],
            'description':r['weather'][0]['description'],
            'icon':r['weather'][0]['icon'],
        }
        cities_whether.append(city_weather)

    context={
        'city_weather':cities_whether,
        'form':form,
        'message':message,
        'message_class':message_class,
    }

    return render(request,'weather/weather.html',context)

def delete_city(request,city_name):
    City.objects.get(name=city_name).delete()
    return redirect('weather:weather_home')

templates/weather/weather.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>بررسی آب و هوا</title>
</head>
<body>

<div class="container"><h1 class="text-center">بررسی آب وهوا</h1></div>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="form-group inline-group">
            {{ form.name }}
            <button type="submit" class="btn  btn-primary " id="btn">بررسی</button>
        </div>

        {% if message %}
            <div class="notification {{ message_class }}">
                {{ message }}
            </div>
        {% endif %}

    </form>
</div>
<div class="container" id="container">
    <div class="card">
        {% for i in city_weather %}
            <div class="card-body">
                <h5 class="card-title">{{ i.city }}</h5>
                <h6 class="card-subtitle mb-2">وضعیت جوی این شهر: {{ i.temperature }} °F</h6>
                <p class="card-text">{{ i.description }}</p>
                <div id="img-container"> نمای جوی<img src="http://openweathermap.org/img/w/{{ i.icon }}.png">
                </div>
            </div>
            <div class="media-right">
                <a href="{% url 'weather:delete_city' i.city %}">
                    <button class="delete"></button>
                </a>
            </div>
        {% endfor %}

    </div>

</div>

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/bootsnav.css' %}">
<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
</body>
</html>